version: "3.9"

services:
  database:
    container_name: database
    image: "percona:ps-8"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-news_parsing_service}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3307:3306"
    networks:
      - app-tier
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
    links:
      - database
      - rabbitmq
    networks:
      - app-tier

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - app-tier

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.11-management"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-tier

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "3000:8080"
    depends_on:
      - database
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
